# Generated by Django 4.2.3 on 2023-07-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_user', '0002_empuser_created_by_empuser_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('in_punch_time', models.TimeField()),
                ('out_punch_time', models.TimeField()),
                ('marked_by', models.CharField(default='admin', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_user.empuser')),
            ],
        ),
    ]
