# Generated by Django 4.2.3 on 2023-07-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0003_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
