# Generated by Django 4.2.3 on 2023-07-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_user', '0005_alter_salary_total_income'),
        ('staff_user', '0004_remove_attendance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_user.empuser')),
            ],
        ),
    ]
