# Generated by Django 4.2.3 on 2023-07-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_user', '0002_empuser_created_by_empuser_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DA_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Allowances_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.CharField(default='admin', max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='admin', max_length=255)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_user.empuser')),
            ],
        ),
    ]
