# Generated by Django 4.2.3 on 2023-07-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_user', '0003_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_dt',
        ),
    ]
