# Generated by Django 4.2.3 on 2023-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_user', '0004_remove_salary_created_by_remove_salary_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
